
# game settings
WINDOW_SIZE = (800, 500)

# background settings
GROUND_SPEED = 10
SKY_SPEED = 1
BUILDING1_SPEED = 3
BUILDING2_SPEED = 2

# score settings
SCORE_POSITION = (400,110)

# obstacle settings
BARRIER_SPEED = GROUND_SPEED
BARRIER_SIZE = (84, 100)
BARRIER_POS = (WINDOW_SIZE[0], 305)

FIRE_HYDRANT_SPEED = GROUND_SPEED
FIRE_HYDRANT_SIZE = (52, 72)
FIRE_HYDRANT_POS = (WINDOW_SIZE[0], 330)
FIRE_HYDRANT_RANDOM_OFFSET = 100

PLANE_SPEED = 12
PLANE_SIZE = (72, 40)
PLANE_POS = (WINDOW_SIZE[0], 100)

# anya settings
ANYA_JUMP_SPEED = -19.5
ANYA_POS = (100,293)
ANYA_SIZE = () # TODO