# game settings
WINDOW_SIZE = (800, 500)

# background settings
GROUND_SPEED = 10
SKY_SPEED = 1

# score settings
SCORE_POSITION = (400,110)

# obstacle settings
BARRIER_SPEED = GROUND_SPEED
BARRIER_SIZE = (84, 100)
BARRIER_POS = (WINDOW_SIZE[0], 305)

FIRE_HYDRANT_SPEED = GROUND_SPEED
FIRE_HYDRANT_SIZE = (52, 72)
FIRE_HYDRANT_POS = (WINDOW_SIZE[0], 330)

PLANE_SPEED = 10.5
PLANE_SIZE = (72, 40)
PLANE_POS = (WINDOW_SIZE[0], 100)

# anya settings
ANYA_JUMP_SPEED = -19
ANYA_POS = (100,283)
ANYA_SIZE = () # TODO